import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import FormPassword from '@/components/FormPassword'
import DeleteRepeatedWords from '@/components/DeleteRepeatedWords'
import Counter from '@/components/Counter'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
       <FormPassword></FormPassword>
       <br></br>
       <br></br>
       <DeleteRepeatedWords></DeleteRepeatedWords>
       <br></br>
       <br></br>
       <Counter></Counter>
      </main>
    </>
  )
}
